{% set name = "ipyvizzu" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyvizzu-{{ version }}.tar.gz
  sha256: 0783c860b644c04a3cf68fc20a980145a718ddce1a97cf0f5a6c67663f03f1ce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pdm-backend
  run:
    - python >={{ python_min }}
    - typing_extensions
    - ipython
    - jsonschema

test:
  imports:
    - ipyvizzu
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ipyvizzu.vizzuhq.com
  summary: Build animated charts in Jupyter Notebook and similar environments with a simple Python syntax.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Build animated charts in Jupyter Notebook and similar environments with a simple Python syntax.

    [![gif][_gif]](https://ipyvizzu.vizzuhq.com)

    [_gif]: https://ipyvizzu.vizzuhq.com/latest/assets/ipyvizzu-promo.gif

    PyPI: [https://badge.fury.io/py/ipyvizzu](https://badge.fury.io/py/ipyvizzu)

  doc_url: https://ipyvizzu.vizzuhq.com
  dev_url: https://github.com/vizzuhq/ipyvizzu

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - veghdev
