{% set name = "ipyvizzu" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyvizzu-{{ version }}.tar.gz
  sha256: 5eb23f1e118bfd741d0f534189d8356508890879bd4c46011bcb909a1a00853a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ipython
    - pandas
    - jsonschema

test:
  imports:
    - ipyvizzu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vizzuhq/ipyvizzu
  summary: ipyvizzu is the Jupyter Notebook integration of Vizzu.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    ipyvizzu is the Jupyter Notebook integration of Vizzu.

    [![gif][_gif]](https://github.com/vizzuhq/ipyvizzu)

    [_gif]: https://github.com/vizzuhq/ipyvizzu/raw/main/docs/assets/ipyvizzu-promo.gif

    PyPI: [https://badge.fury.io/py/ipyvizzu](https://badge.fury.io/py/ipyvizzu)

  doc_url: https://ipyvizzu.vizzuhq.com/
  dev_url: https://github.com/vizzuhq/ipyvizzu

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - veghdev
