{% set name = "ipyvizzu" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyvizzu-{{ version }}.tar.gz
  sha256: 3503a8fac581bd3b7c7675377224c20a30ef0410473a5e03250c26bcfffbe8d6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pdm-backend
  run:
    - python >=3.6
    - typing_extensions  # [py<38]
    - ipython
    - jsonschema

test:
  imports:
    - ipyvizzu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ipyvizzu.vizzuhq.com
  summary: Build animated charts in Jupyter Notebook and similar environments with a simple Python syntax.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Build animated charts in Jupyter Notebook and similar environments with a simple Python syntax.

    [![gif][_gif]](https://ipyvizzu.vizzuhq.com)

    [_gif]: https://ipyvizzu.vizzuhq.com/latest/assets/ipyvizzu-promo.gif

    PyPI: [https://badge.fury.io/py/ipyvizzu](https://badge.fury.io/py/ipyvizzu)

  doc_url: https://ipyvizzu.vizzuhq.com
  dev_url: https://github.com/vizzuhq/ipyvizzu

extra:
  recipe-maintainers:
    - sugatoray
    # maintainers from upstream repo
    - veghdev
